### ISSUE TITLE
CNAME domain problem

### ISSUE THREAD

**Issue by dhyegocalota** [braziljs/front-in-cuiaba#2]
I'm trying to get access through `http://frontincuiaba.com.br/` and I just can't without prefix `www.`. I think one of the CNAME domain settings could be missing.

**Comment by gpedro** [comment]
nops, it's working. Please clear your cache and try again. Look this commit 29f3cb4a32f66625c63b16d5393064d0b9f05a19
He pointing frontincuiaba.com.br (without www) to www. 

Cleaning Cache:
- [OS X](http://support.apple.com/en-us/HT202516)
- [Linux](http://www.cyberciti.biz/faq/rhel-debian-ubuntu-flush-clear-dns-cache/)
- [Windows](http://www.tech-recipes.com/rx/233/clear_windows_dns_cache/)

**Comment by dhyegocalota** [comment]
I see it's configured correctly but I just can't get access. Do you can get any access?

**Comment by gpedro** [comment]
Resolved.

**Comment by dhyegocalota** [comment]
Thanks man.
