### ISSUE TITLE
Add speakers' slides link

### ISSUE THREAD

**Issue by juarezpaf** [braziljs/front-in-cuiaba#5]
## Speakers' Slides
- Alvaro Viebrantz http://alvarowolfx.github.io/ionic-present
- Almir Filho https://speakerdeck.com/almirfilho/esse-cara-e-o-grunt
- Dhyego Fernando http://dhyegofernando.github.io/modular-angularjs-talk
- Davidson Fellipe http://www.slideshare.net/davidsonfellipe/guia-do-front-end-das-galaxias
- Karuan Bertoluci https://medium.com/@karuanbertoluci/inovacao-e-experiencia-de-usuario-8c7f99bbfb73

**Comment by kivervinicius** [comment]
Thanks for that, my congratulations to all the organizers of the event, you are all to be congratulated!
